[build-system]
requires = ["setuptools>=68", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "kumacord"
version = "0.1.0"
description = "Uptime Kuma to Discord Dashboard bot"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
  "discord.py==2.6.4",
  "aiohttp==3.13.3",
  "python-dotenv==1.2.1",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
